# These urls will be replaced in DEV mode

go:
  apps:
    - name: mux-test-app
      url: https://url-from-serverless # Serverless URL

nodejs:
  apps:
    - name: express-test-app
      url: https://url-from-serverless # Serverless URL

python:
  apps:
    # - name: django-test-app
    #   url: https://resurface-django.herokuapp.com # Serverless URL
    # - name: flask-test-app
    #   url: https://resurface-flask.herokuapp.com # Serverless URL
    - name: aiohttp-test-app
      url: https://aiohttp-resurface.herokuapp.com # Serverless URL
    # - name: fastapi-test-app
    #   url: https://url-from-serverless # Serverless URL
    # - name: tornado-test-app
    #   url: https://url-from-serverless # Serverless URL
