# These urls will be replaced in DEV mode

go:
  apps:
    - name: mux-test-app
      url: https://url-from-serverless # Serverless URL

nodejs:
  apps:
    - name: express-test-app
      url: https://url-from-serverless # Serverless URL

python:
  apps:
    - name: django-test-app
      url: https://url-from-serverless # Serverless URL
    #- name: flask-test-app
    #  url: https://url-from-serverless # Serverless URL
    #- name: aiohttp-test-app
    #  url: https://url-from-serverless # Serverless URL
    # - name: fastapi-test-app
    #   url: https://url-from-serverless # Serverless URL
    # - name: tornado-test-app
    #   url: https://url-from-serverless # Serverless URL
