payloads:
  - url: RESURFACE_PLACEHOLDER/ping
    payload_number: 0
    type: REST # or GQL
    method: GET
    response_status: 200
    descriptions: Test RESTful ping
    response_body: |
      {
        "msg": "pong"
      }

  - url: RESURFACE_PLACEHOLDER/
    payload_number: 1
    type: GQL
    method: POST
    response_status: 200
    descriptions: Graphql mutation to empty DB
    request_body: |
      mutation{
        deleteEverything{
          ok
        }
      }
    response_body: |
      {
        "data": {
          "deleteEverything": {
            "ok": true
          }
        }
      }

  - url: RESURFACE_PLACEHOLDER/
    payload_number: 2
    type: GQL
    method: POST
    response_status: 200
    descriptions: Graphql query to get empty news
    request_body: |
      query{
          allNews{
            id
          }
        }
    response_body: |
      {
        "data": {
          "allNews": []
        }
      }

  - url: RESURFACE_PLACEHOLDER/
    payload_number: 3
    type: GQL
    method: POST
    response_status: 200
    descriptions: Graphql mutation to add data
    request_body: |
      mutation{
          addNews(title: "This is a great short news!", body: "body here"){
            news{
              title
              body
            }
          }
        }
    response_body: |
      {
        "data": {
          "addNews": {
            "news": {
              "title": "This is a great short news!",
              "body": "body here"
            }
          }
        }
      }

  - url: RESURFACE_PLACEHOLDER/
    payload_number: 4
    type: GQL
    method: POST
    response_status: 200
    descriptions: Graphql query to get news data
    request_body: |
      query{
          allNews{
            title
          }
        }
    response_body: |
      {
        "data": {
          "allNews": [
            {
              "title": "This is a great short news!"
            }
          ]
        }
      }
